#ifndef key_defs_h
#define key_defs_h

#define KEY_AUDIO                0x64
#define KEY_SHUFFLE              0x35
#define KEY_ANGLE                0x65
#define KEY_PROGRAM              0x1F
#define KEY_SUBTITLE             0x63
#define KEY_REPEAT               0x2C
#define KEY_SLOW_L               0x60
#define KEY_SLOW_R               0x61
#define KEY_CLEAR                0x0F
#define KEY_TIME                 0x28
#define KEY_SCAN_L               0x33
#define KEY_SCAN_R               0x34
#define KEY_PREV                 0x30
#define KEY_NEXT                 0x31
#define KEY_A_B                  0x2A
#define KEY_PLAY                 0x32
#define KEY_PAUSE                0x39
#define KEY_STOP                 0x38
#define KEY_DISPLAY              0x54
#define KEY_TITLE                0x1A
#define KEY_DVD_MENU             0x1B
#define KEY_RETURN               0x0E
#define KEY_TRIANGLE             0x5C
#define KEY_CIRCLE               0x5D
#define KEY_SQUARE               0x5F
#define KEY_X                    0x5E
#define KEY_UP_0                 0x54
#define KEY_UP_1                 0x79
#define KEY_DOWN_0               0x56
#define KEY_DOWN_1               0x7A
#define KEY_LEFT_0               0x57
#define KEY_LEFT_1               0x7B
#define KEY_RIGHT_0              0x55
#define KEY_RIGHT_1              0x7C
#define KEY_ENTER                0x0B
#define KEY_L1                   0x5A
#define KEY_L2                   0x58
#define KEY_L3                   0x51
#define KEY_R1                   0x5B
#define KEY_R2                   0x59
#define KEY_R3                   0x52
#define KEY_SELECT               0x50
#define KEY_START                0x53
#define KEY_1                    0x00
#define KEY_2                    0x01
#define KEY_3                    0x02
#define KEY_4                    0x03
#define KEY_5                    0x04
#define KEY_6                    0x05
#define KEY_7                    0x06
#define KEY_8                    0x07
#define KEY_9                    0x08
#define KEY_0                    0x09
#define KEY_POWER                0x15
#define KEY_EJECT                0x16
#define KEY_POWERON              0x2E
#define KEY_POWEROFF             0x2F

#define KEY_MAGIC_DEFAULT        KEY_ANGLE



#define CPLD_EJECT          0x01
#define CPLD_1              0x04
#define CPLD_2              0x05
#define CPLD_3              0x10
#define CPLD_AUDIO          0x11
#define CPLD_TRIANGLE       0x14
#define CPLD_UP             0x15
#define CPLD_4              0x03
#define CPLD_5              0x06
#define CPLD_6              0x07
#define CPLD_ANGLE          0x12
#define CPLD_7              0x13
#define CPLD_CIRCLE         0x16
#define CPLD_LEFT           0x17
#define CPLD_8              0x09
#define CPLD_9              0x0C
#define CPLD_SUBTITLE       0x0D
#define CPLD_CLEAR          0x18
#define CPLD_0              0x19
#define CPLD_ENTER          0x1C
#define CPLD_RIGHT          0x1D
#define CPLD_TIME           0x0B
#define CPLD_SHUFFLE        0x0E
#define CPLD_PROGRAM        0x0F
#define CPLD_REPEAT         0x1A
#define CPLD_A_B            0x1B
#define CPLD_SQUARE         0x1E
#define CPLD_DOWN           0x1F
#define CPLD_DISPLAY        0x21
#define CPLD_DVD_MENU       0x24
#define CPLD_TITLE          0x25
#define CPLD_RETURN         0x30
#define CPLD_SCAN_B         0x31
#define CPLD_X              0x34
#define CPLD_L1             0x35
#define CPLD_PLAY           0x23
#define CPLD_SCAN_F         0x26
#define CPLD_L3             0x27
#define CPLD_PREV           0x32
#define CPLD_STOP           0x33
#define CPLD_POWER_RESET    0x36
#define CPLD_R1             0x37
#define CPLD_NEXT           0x29
#define CPLD_SLOW_B         0x2C
#define CPLD_PAUSE          0x2D
#define CPLD_SELECT         0x38
#define CPLD_SLOW_F         0x39
#define CPLD_L2             0x3C
#define CPLD_R2             0x3D
#define CPLD_POWERON        0x00
#define CPLD_POWEROFF       0x00
#define CPLD_R3             0x2B
#define CPLD_START          0x2E

#define CPLD_HARD_RESET     0x00

#endif
